# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mantis < Formula
  desc "Local-first codebase intelligence engine — dependency graph, LLM context, architecture lint"
  homepage "https://github.com/seedhire/mantis"
  version "0.5.11"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/seedhire/mantis/releases/download/v0.5.11/mantis_darwin_amd64.tar.gz"
    sha256 "522a55742f12a1363b920d30fc2691db3199b0d24b8865c890407626651c11f1"

    define_method(:install) do
      bin.install "mantis"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/seedhire/mantis/releases/download/v0.5.11/mantis_darwin_arm64.tar.gz"
    sha256 "cae18ee857836fe238a70b5454ee177c2312504001af92016cd8c2f68485715d"

    define_method(:install) do
      bin.install "mantis"
    end
  end

  test do
    system "#{bin}/mantis", "--help"
  end
end
