# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mantis < Formula
  desc "Local-first codebase intelligence engine — dependency graph, LLM context, architecture lint"
  homepage "https://github.com/seedhire/mantis"
  version "0.7.12"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/seedhire/mantis/releases/download/v0.7.12/mantis_darwin_amd64.tar.gz"
    sha256 "60e6205e4342b165e7bd9168f477016f97adc085b217b44e94ca6971c6fbbaad"

    define_method(:install) do
      bin.install "mantis"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/seedhire/mantis/releases/download/v0.7.12/mantis_darwin_arm64.tar.gz"
    sha256 "5b5ce3a4af49dbc43baaa160c2a5123f3c6b617c2d9679ee0789779fa5d92677"

    define_method(:install) do
      bin.install "mantis"
    end
  end

  test do
    system "#{bin}/mantis", "--help"
  end
end
